language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.3
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
install:
  - pip install --timeout=30 -q Django==$DJANGO --use-mirrors
  - pip install --timeout=30 pep8 --use-mirrors
  - pip install --timeout=30 https://github.com/dcramer/pyflakes/tarball/master
  - pip install --timeout=30 -q -e . --use-mirrors
before_script:
  - make verify
script:
  - make test
